import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Every entry whatran writes into somebody else's config carries this flag, and
// nothing is ever removed without it.
//
// The previous version matched the substring "whatran" anywhere in the
// serialised config. That deleted a user's own unrelated hook whose command
// merely referenced a path containing the word, demonstrated, silently, with
// no way to get it back. Never identify your own data in someone else's file by
// guessing at its contents.
const OWNED = '_whatran';

// The same idea for the markdown command file, which cannot carry a JSON key.
const MD_MARKER = '<!-- _whatran: generated by `whatran init`. Delete this line to keep it. -->';

// The hook config has to name a command that will actually resolve months from
// now, on a machine that may never have installed anything. Writing
// `npx whatran` when the package is not published, or is only checked out
// locally, produces a config that silently does nothing, which is worse than
// one that fails loudly.
export function hookCommand(root, version) {
  const binPath = fileURLToPath(new URL('../bin/whatran.js', import.meta.url));
  const segments = binPath.split(path.sep);

  // npx caches packages under <npm-cache>/_npx/<hash>/node_modules/<pkg>, so
  // "is it under node_modules" wrongly reported an npx run as a real install
  // and wrote `npx --no-install whatran hook`, which errors out, because the
  // package is not in the project. Claude Code treats a non-zero, non-2 exit as
  // a silent non-blocking error, so the hook died quietly and forever while
  // init reported success.
  //
  // Pinned to the version doing the installing. An unpinned `npx whatran` in a
  // committed config means every teammate silently gets whatever is newest,
  // including a version whose baseline format has changed.
  if (segments.includes('_npx')) {
    return { command: `npx --yes whatran@${version ?? 'latest'} hook`, ephemeral: true };
  }

  // A project-local install: relative, so it survives being committed and
  // works for every teammate.
  if (root) {
    const rel = path.relative(root, binPath);
    if (segments.includes('node_modules') && rel && !rel.startsWith('..')) {
      return { command: `node ${quote(rel.split(path.sep).join('/'))} hook`, ephemeral: false };
    }
  }

  // Running from a clone: point straight at this checkout with the interpreter
  // running right now. Absolute and machine-specific, so it must not be
  // committed; `local: true` sends it to the settings file git ignores.
  return {
    command: `${quote(posix(process.execPath))} ${quote(posix(binPath))} hook`,
    ephemeral: false,
    local: true,
  };
}

// Windows accepts forward slashes everywhere, and a backslash path written into
// a config that some harness feeds to a POSIX shell is destroyed by it.
const posix = (p) => p.split(path.win32.sep).join('/');

// Always quoted. Quoting only when a space happens to be present meant the
// command worked on the developer's machine and broke on the first user whose
// home directory had one in it.
function quote(p) {
  return `"${p.replace(/(["\\$`])/g, '\\$1')}"`;
}

// Hook wiring for each harness that supports acting at the end of a turn.
const TARGETS = [
  {
    id: 'claude',
    label: 'Claude Code',
    file: '.claude/settings.json',
    localFile: '.claude/settings.local.json',
    detect: (root) => fs.existsSync(path.join(root, '.claude')) || fs.existsSync(path.join(root, 'CLAUDE.md')),
    build: (existing, cmd) => {
      const doc = existing ?? {};
      doc.hooks ??= {};
      addHook(doc.hooks, 'SessionStart', {
        [OWNED]: true,
        hooks: [{
          type: 'command',
          command: cmd + ' --event SessionStart',
          // Recording the baseline must not delay the first prompt either.
          async: true,
          timeout: 900,
          statusMessage: 'whatran is recording what your suite runs',
        }],
      });
      addHook(doc.hooks, 'Stop', {
        [OWNED]: true,
        hooks: [{
          type: 'command',
          command: cmd,
          // The whole point. A test suite takes minutes; blocking the turn on
          // it makes the tool unusable on any real repository. asyncRewake
          // runs it in the background, ends the turn immediately, and wakes
          // the agent only if the check exits 2, showing it our stderr.
          //
          // Backgrounding applies to interactive and streaming sessions. In a
          // non-interactive run (`claude -p`, CI) the hook is synchronous, so
          // `timeout` below is the real ceiling there and whatran's own budget
          // in whatran.js is the ceiling everywhere else.
          asyncRewake: true,
          timeout: 900,
          statusMessage: 'whatran is checking what your suite ran',
        }],
      });
      return doc;
    },
  },
  {
    id: 'codex',
    label: 'Codex CLI',
    file: '.codex/hooks.json',
    // Deliberately NOT AGENTS.md. That file is now a cross-tool convention that
    // half a dozen agents read, so treating it as evidence of Codex wrote
    // .codex/hooks.json into repositories that have never run Codex once.
    detect: (root) => fs.existsSync(path.join(root, '.codex')),
    // Codex will not execute a hook until the user has trusted it, and there is
    // no way to grant that from here. Saying "installed" without saying so
    // reports protection that is not switched on.
    note: 'Codex will not run it until you trust it: open Codex, run /hooks, and trust the whatran entry',
    build: (existing, cmd) => {
      const doc = existing ?? {};
      doc.hooks ??= {};
      addHook(doc.hooks, 'Stop', {
        [OWNED]: true,
        hooks: [{ type: 'command', command: cmd + ' --harness codex', timeout: 900 }],
      });
      return doc;
    },
  },
  {
    id: 'cursor',
    label: 'Cursor',
    file: '.cursor/hooks.json',
    detect: (root) => fs.existsSync(path.join(root, '.cursor')),
    build: (existing, cmd) => {
      const doc = existing ?? { version: 1 };
      doc.hooks ??= {};
      // Cursor's stop hook cannot block and cannot read stderr: its only
      // channel is a `followup_message` on stdout. The hook has to be told
      // which harness invoked it, because it has no other way to know.
      doc.hooks.stop ??= [];
      if (!doc.hooks.stop.some(isOurs)) {
        doc.hooks.stop.push({ [OWNED]: true, command: cmd + ' --harness cursor' });
      }
      return doc;
    },
  },
];

function isOurs(entry) {
  return Boolean(entry && typeof entry === 'object' && entry[OWNED] === true);
}

function addHook(hooks, event, entry) {
  hooks[event] ??= [];
  const at = hooks[event].findIndex(isOurs);
  // Replaced rather than skipped, so a config carrying an entry from an older
  // version, or one where only half the events were written, is repaired
  // instead of being left half-installed forever.
  if (at === -1) hooks[event].push(entry);
  else hooks[event][at] = entry;
}

// True when this config already carries our entry for every event we install,
// with the command we would write now. A bare marker anywhere used to satisfy
// this, so a partially installed config was never repaired and a stale command
// was never upgraded.
function upToDate(doc, target, cmd) {
  const built = target.build(structuredClone(doc ?? {}), cmd);
  return JSON.stringify(built) === JSON.stringify(doc);
}

// Config belonging to someone else. Written the same way as the baseline:
// to a sibling, then renamed, so an interrupted run cannot leave a truncated
// settings file behind and stop their agent from starting.
function writeJsonAtomic(file, doc) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tmp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify(doc, null, 2) + '\n');
  try {
    fs.renameSync(tmp, file);
  } catch (err) {
    try { fs.rmSync(tmp, { force: true }); } catch { /* ignore */ }
    throw err;
  }
}

// A settings.json saved by a Windows editor often starts with a byte order
// mark, which JSON.parse rejects. Refusing to touch the file then reported it
// as "not valid JSON", and uninstall claimed there was nothing to remove.
function readJson(file) {
  const raw = fs.readFileSync(file, 'utf8').replace(/^\uFEFF/, '');
  if (!raw.trim()) return {};
  return JSON.parse(raw);
}

// The `/whatran` slash command. Generated from a string rather than shipped as
// a template file on purpose: package.json's `files` list ships bin/ and src/
// only, so a templates/ directory would work in a clone and be silently missing
// for every `npx whatran init` user.
function commandFile(cmd) {
  return `---
description: Check what the test suite actually ran, and fix anything that stopped running.
argument-hint: "[--base <ref>]"
allowed-tools: Bash, Read, Edit, Grep, Glob
---

${MD_MARKER}

## What the suite is running now

!\`${cmd.replace(/ hook$/, '')} check --json $ARGUMENTS\`

## Your task

The JSON above is the result of comparing what this project's test suite ran
before the current change with what it runs now. It is measured, not inferred:
each entry names a test by id and says what happened to it.

Read \`verdict\` and \`findings\`, then:

- **\`inconclusive\` is not null** — whatran could not obtain trustworthy
  evidence and is making no claim. Tell the user the reason verbatim and what
  would let it run. Do not guess at the answer it could not reach.
- **\`missing\` findings** — something that used to run does not run any more.
  This is the one that matters: the suite is green because those tests stopped
  reporting. Fix the underlying code so each named test runs and passes again.
  Do not skip, delete, rename around, or exclude them, and do not edit the test
  configuration to make the finding go away.
- **\`broke\` findings** — a test that passed now fails. Fix the code, not the
  test, unless changing that behaviour was the point of the task, in which case
  say so explicitly.
- **\`notice\` findings** — worth a look, often legitimate. Mention them; act
  only where it is clearly right.
- **\`intact\`, and no findings** — say so in one line and stop. Do not invent
  work.

When you have made a change, re-run this command and confirm by name that each
test listed now runs and passes. Report what you actually saw.

If you conclude a test genuinely should no longer exist, leave it in place and
explain your reasoning to the user. \`whatran accept\` would clear the finding
without fixing anything, so that decision is the user's, not yours.
`;
}

export function installHooks(root, { version } = {}) {
  const out = { lines: [], installed: 0, failed: 0 };
  const cmd = hookCommand(root, version);
  const targets = TARGETS.filter((t) => t.detect(root));

  if (!targets.length) {
    // Writing config for a harness that is not here is exactly the behaviour
    // people resent in other tools. Say what to do instead.
    out.lines.push('· no agent harness detected here, nothing installed');
    out.lines.push('  looked for .claude/, CLAUDE.md, .codex/ and .cursor/');
    out.lines.push('  run `whatran` yourself, or add it to CI with `whatran check --base main`');
    return out;
  }

  for (const t of targets) {
    // A machine-specific absolute path must not be committed. The target
    // declared a local settings file for exactly this case and never used it,
    // so `init` from a clone wrote this machine's node path into the shared
    // .claude/settings.json and every teammate inherited a broken hook.
    const rel = cmd.local && t.localFile ? t.localFile : t.file;
    const file = path.join(root, rel);
    let existing = null;
    if (fs.existsSync(file)) {
      try { existing = readJson(file); } catch {
        out.lines.push(`! ${rel} exists but is not valid JSON, left untouched`);
        out.failed++;
        continue;
      }
      if (upToDate(existing, t, cmd.command)) {
        out.lines.push(`· ${t.label} hook already installed`);
        out.installed++;
        if (t.note) out.lines.push(`  ! ${t.note}`);
        continue;
      }
    }
    try {
      writeJsonAtomic(file, t.build(existing, cmd.command));
      out.lines.push(`+ ${t.label} hook installed (${rel})`);
      out.installed++;
      if (cmd.local) {
        out.lines.push('  (an absolute path to this checkout, so it is written to the local, uncommitted settings file)');
      }
      if (t.note) out.lines.push(`  ! ${t.note}`);
    } catch (err) {
      out.lines.push(`! could not write ${rel}: ${err.message}`);
      out.failed++;
    }

    if (t.id === 'claude') installCommand(root, cmd.command, out);
  }
  suggestGitignore(root, out.lines);
  return out;
}

// `/whatran` for Claude Code. Never overwrites a file it did not write: the
// same rule the OWNED marker enforces for JSON.
function installCommand(root, cmd, out) {
  const rel = '.claude/commands/whatran.md';
  const file = path.join(root, rel);
  if (fs.existsSync(file)) {
    let body = '';
    try { body = fs.readFileSync(file, 'utf8'); } catch { /* unreadable */ }
    if (!body.includes(MD_MARKER)) {
      out.lines.push(`· ${rel} already exists and is not ours, left untouched`);
      return;
    }
  }
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, commandFile(cmd));
    out.lines.push(`+ /whatran command installed (${rel})`);
  } catch (err) {
    out.lines.push(`! could not write ${rel}: ${err.message}`);
  }
}

export function uninstallHooks(root) {
  const out = [];
  for (const t of TARGETS) {
    for (const rel of [t.file, t.localFile].filter(Boolean)) {
      const file = path.join(root, rel);
      if (!fs.existsSync(file)) continue;
      let doc;
      try { doc = readJson(file); } catch { continue; }
      const removed = stripOwned(doc);
      if (!removed) continue;
      // Removing our entry can leave an empty event array that only existed
      // because we created it. Leaving litter in someone else's config is a
      // small rudeness, and it means uninstall does not truly undo install.
      pruneEmpty(doc);
      try {
        writeJsonAtomic(file, doc);
        out.push(`- ${t.label} hook removed (${rel})`);
      } catch (err) {
        out.push(`! could not write ${rel}: ${err.message}`);
      }
    }
  }

  const cmdFile = path.join(root, '.claude/commands/whatran.md');
  try {
    if (fs.readFileSync(cmdFile, 'utf8').includes(MD_MARKER)) {
      fs.rmSync(cmdFile);
      out.push('- /whatran command removed (.claude/commands/whatran.md)');
    }
  } catch { /* absent, unreadable, or somebody else's */ }

  if (!out.length) out.push('· no whatran hooks found');
  return out;
}

// Removes only entries whatran itself marked. Returns how many went.
function stripOwned(node) {
  let removed = 0;
  if (Array.isArray(node)) {
    for (let i = node.length - 1; i >= 0; i--) {
      if (isOurs(node[i])) { node.splice(i, 1); removed++; }
      else removed += stripOwned(node[i]);
    }
  } else if (node && typeof node === 'object') {
    for (const v of Object.values(node)) removed += stripOwned(v);
  }
  return removed;
}

// Deliberately does NOT edit the user's .gitignore. Appending to a file nobody
// asked you to touch is the most-resented behaviour in tools of this kind.
// saveBaseline already writes `.whatran/.gitignore` containing `*`, which is
// self-contained and is the convention ruff and pytest both use, so this is a
// suggestion for people who would rather have it listed in one place.
function suggestGitignore(root, out) {
  const gi = path.join(root, '.gitignore');
  let text = '';
  try { text = fs.readFileSync(gi, 'utf8'); } catch { /* none yet */ }
  if (text.split(/\r?\n/).some((l) => l.trim() === '.whatran/' || l.trim() === '.whatran')) return;
  out.push('· .whatran/ already ignores itself; add it to .gitignore only if you prefer it listed there');
}

// Drops event keys under `hooks` whose array is now empty, and `hooks` itself
// if nothing is left in it.
function pruneEmpty(doc) {
  const hooks = doc && typeof doc === 'object' ? doc.hooks : null;
  if (!hooks || typeof hooks !== 'object') return;
  for (const [event, entries] of Object.entries(hooks)) {
    if (Array.isArray(entries) && entries.length === 0) delete hooks[event];
  }
  if (!Object.keys(hooks).length) delete doc.hooks;
}

// Which harnesses are wired up right now, for `whatran status`.
export function installedTargets(root) {
  const found = [];
  for (const t of TARGETS) {
    for (const rel of [t.file, t.localFile].filter(Boolean)) {
      const file = path.join(root, rel);
      if (!fs.existsSync(file)) continue;
      let doc;
      try { doc = readJson(file); } catch { continue; }
      let has = false;
      walk(doc, (n) => { if (isOurs(n)) has = true; });
      if (has) found.push({ id: t.id, label: t.label, file: rel, note: t.note ?? null });
    }
  }
  return found;
}

function walk(node, fn) {
  if (Array.isArray(node)) { for (const v of node) { fn(v); walk(v, fn); } return; }
  if (node && typeof node === 'object') {
    fn(node);
    for (const v of Object.values(node)) walk(v, fn);
  }
}

export const __test = { MD_MARKER, commandFile, quote };
