import { changedFiles } from './git.js';

// Extensions that cannot change a test outcome no matter what they contain.
// The list is deliberately a strict allow-list of INERT things: anything not
// recognised counts as relevant, so an unfamiliar file type causes a check to
// run rather than to be silently skipped. Being wrong in that direction costs
// time; being wrong the other way costs a missed regression.
//
// Note what is NOT here any more. `.gitignore` was: adding one pattern changes
// what every file-based check in this tool can see, so an agent could add a
// conftest.py and an ignore rule for it in the same turn and the whole check
// would be skipped as irrelevant. Dependency lockfiles were classed as build
// artefacts, which made a turn that only bumped Cargo.lock or poetry.lock skip
// the suite entirely, when changing a dependency version is one of the most
// direct ways there is to change a test outcome.
const INERT = new Set([
  '.md', '.markdown', '.mdx', '.rst', '.adoc', '.txt',
  '.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.ico', '.pdf',
  '.woff', '.woff2', '.ttf', '.otf', '.eot',
  '.mp4', '.webm', '.mp3', '.wav',
  '.gitattributes', '.editorconfig', '.npmignore',
]);

const INERT_NAMES = new Set([
  'LICENSE', 'LICENCE', 'NOTICE', 'AUTHORS', 'CONTRIBUTORS',
  'CHANGELOG', 'CODEOWNERS', '.gitattributes', '.editorconfig',
]);

// Documentation and images stop being inert inside test territory. A golden
// .txt, a visual-regression .png, an .mdx the docs tests render and a fixture
// .md a doctest reads all decide test outcomes directly, and treating them as
// inert skipped the suite on exactly the turn that changed the expected answer.
const TEST_TERRITORY =
  /(^|\/)(tests?|__tests__|spec|specs|fixtures?|__fixtures__|golden|goldens|testdata|snapshots?|__snapshots__|e2e|integration)\//i;

// Build outputs and caches, from the point of view of "the test run itself
// wrote this". These are regenerated by the act of running the suite, so a repo
// that does not ignore them would otherwise look changed on every single turn.
//
// They are NOT the same list as "cannot affect a test": a repo whose tests
// import from dist/ is perfectly ordinary, and calling that irrelevant meant
// skipping the suite on a change that certainly could break it. The two
// questions are asked separately below.
const VOLATILE_EXTS = new Set([
  '.pyc', '.pyo', '.pyd', '.class', '.o', '.obj', '.a', '.lib', '.map',
  '.log', '.tsbuildinfo', '.orig',
]);

const VOLATILE_DIRS = [
  '__pycache__/', '.pytest_cache/', '.mypy_cache/', '.ruff_cache/', '.tox/',
  'node_modules/', 'dist/', 'build/', 'coverage/', 'htmlcov/', '.nyc_output/',
  'target/debug/', 'target/release/', '.gradle/', '.next/', '.turbo/',
  'test-results/', 'playwright-report/', '.vitest-cache/', '.cache/',
];

const VOLATILE_NAMES = new Set([
  'junit.xml', 'coverage.xml', '.coverage', 'lcov.info', 'test-report.xml',
]);

// The baseline itself changes on every snapshot; it must never trigger a run.
// Agent configuration cannot change a test outcome either.
const IGNORED_PREFIXES = ['.whatran/', '.claude/', '.codex/', '.cursor/'];

const basename = (f) => f.split('/').pop() ?? '';
const extname = (f) => {
  const base = basename(f);
  const dot = base.lastIndexOf('.');
  return dot > 0 ? base.slice(dot).toLowerCase() : '';
};

// True when a test run is what writes this path, so seeing it change tells us
// nothing about what anybody edited.
export function isVolatileFile(f) {
  if (IGNORED_PREFIXES.some((p) => f.startsWith(p))) return true;
  if (VOLATILE_DIRS.some((d) => f.startsWith(d) || f.includes('/' + d))) return true;
  if (VOLATILE_NAMES.has(basename(f))) return true;
  return VOLATILE_EXTS.has(extname(f));
}

// True when this path could plausibly change a test outcome.
export function isRelevantFile(f) {
  if (IGNORED_PREFIXES.some((p) => f.startsWith(p))) return false;
  if (VOLATILE_DIRS.some((d) => f.startsWith(d) || f.includes('/' + d))) return false;
  if (VOLATILE_EXTS.has(extname(f))) return false;
  if (TEST_TERRITORY.test(f)) return true;
  const base = basename(f);
  // Matched only at the repository root, and on the whole filename. Matching a
  // basename anywhere made `src/NOTICE.ts` inert, and stripping the extension
  // first made `CHANGELOG.py` inert, which is an ordinary source file name.
  if (!f.includes('/') && INERT_NAMES.has(base)) return false;
  return !INERT.has(extname(f));
}

// `sinceRef` must be the commit the baseline was recorded at. Without it this
// only sees uncommitted work, and an agent that commits its changes, which
// they routinely do, would sail past the gate with nothing to report.
//
// Returns null when git could not answer, which is NOT the same as "nothing
// changed" and must never be treated as it: a git failure that read as a clean
// turn skipped the suite entirely and, worse, made `check` rewrite real MISSING
// findings into a NOTICE and permanently exempt them as flaky.
export function relevantChanges(root, sinceRef = null) {
  const res = changedFiles(root, sinceRef);
  if (!res.ok) return null;
  return res.files.filter(isRelevantFile);
}

export function couldAffectTests(root, sinceRef = null) {
  const relevant = relevantChanges(root, sinceRef);
  // A git failure returns null: assume relevance rather than skip silently.
  if (relevant === null) return true;
  // An empty list is the other common case, the agent answered a question
  // without editing anything at all.
  return relevant.length > 0;
}

// What the tree fingerprint watches: things a person or an agent could have
// edited mid-run, excluding everything the suite writes for itself.
export function isTrackedEdit(f) {
  return isRelevantFile(f) && !isVolatileFile(f);
}
