import { changedFiles } from './git.js';

// Extensions that cannot change a test outcome no matter what they contain.
// The list is deliberately a strict allow-list of INERT things: anything not
// recognised counts as relevant, so an unfamiliar file type causes a check to
// run rather than to be silently skipped. Being wrong in that direction costs
// time; being wrong the other way costs a missed regression.
const INERT = new Set([
  '.md', '.markdown', '.mdx', '.rst', '.adoc', '.txt',
  '.png', '.jpg', '.jpeg', '.gif', '.svg', '.webp', '.ico', '.pdf',
  '.woff', '.woff2', '.ttf', '.otf', '.eot',
  '.mp4', '.webm', '.mp3', '.wav',
  '.gitignore', '.gitattributes', '.editorconfig', '.npmignore',
]);

const INERT_NAMES = new Set([
  'LICENSE', 'LICENCE', 'NOTICE', 'AUTHORS', 'CONTRIBUTORS',
  'CHANGELOG', 'CODEOWNERS', '.gitignore', '.gitattributes', '.editorconfig',
]);

// Build outputs and caches. These are regenerated by the very act of running
// the suite, so a repo that tracks them (or simply doesn't ignore them) would
// otherwise look "changed" on every single turn and defeat the gate entirely.
// They are outputs, never inputs: if one of them differs, its source differs
// too, and that source is what triggers the run.
const ARTEFACT_EXTS = new Set([
  '.pyc', '.pyo', '.pyd', '.class', '.o', '.obj', '.a', '.lib', '.map',
  '.log', '.lock', '.tsbuildinfo',
]);

const ARTEFACT_DIRS = [
  '__pycache__/', '.pytest_cache/', '.mypy_cache/', '.ruff_cache/', '.tox/',
  'node_modules/', 'dist/', 'build/', 'coverage/', '.nyc_output/',
  'target/debug/', 'target/release/', '.gradle/', '.next/', '.turbo/',
];

// The baseline itself changes on every snapshot; it must never trigger a run.
// Agent configuration cannot change a test outcome either.
const IGNORED_PREFIXES = ['.adjuster/', '.claude/', '.codex/', '.cursor/'];

// True when this path could plausibly change a test outcome.
export function isRelevantFile(f) {
  if (IGNORED_PREFIXES.some((p) => f.startsWith(p))) return false;
  if (ARTEFACT_DIRS.some((d) => f.startsWith(d) || f.includes('/' + d))) return false;
  const base = f.split('/').pop() ?? '';
  const nameNoExt = base.replace(/\.[^.]+$/, '');
  if (INERT_NAMES.has(base) || INERT_NAMES.has(nameNoExt)) return false;
  const dot = base.lastIndexOf('.');
  const ext = dot > 0 ? base.slice(dot).toLowerCase() : '';
  return !INERT.has(ext) && !ARTEFACT_EXTS.has(ext);
}

export function relevantChanges(root) {
  let changed;
  try { changed = changedFiles(root, null); } catch { return null; }
  return changed.filter(isRelevantFile);
}

export function couldAffectTests(root) {
  const relevant = relevantChanges(root);
  // A git failure returns null: assume relevance rather than skip silently.
  if (relevant === null) return true;
  // An empty list is the other common case — the agent answered a question
  // without editing anything at all.
  return relevant.length > 0;
}
